-- [59413] 입양 시각 구하기(2) : https://programmers.co.kr/learn/courses/30/lessons/59413
WITH RECURSIVE HOUR AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM HOUR WHERE H < 23
)
SELECT HOUR.H, COALESCE(COUNT(ANIMAL_ID),0) AS COUNT
FROM ANIMAL_OUTS RIGHT JOIN HOUR
    ON HOUR(DATETIME) = HOUR.H
GROUP BY HOUR.H

```
SET @HOUR = -1;

SELECT (@HOUR:=@HOUR+1) AS HOUR, (
    SELECT COUNT(*)
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @HOUR
) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
```